
## Run version 3.0
```{R}

# Load packages
library(tidyverse)
library(logr)
library(sf)
library(readxl)

# Load functions
source("./script_proximity_for_points_V3.R")
source("./functions/xyz_proximity_points_setup_logging.R")
source("./functions/xyz_proximity_points_input_validation.R")
source("./functions/xyz_proximity_points_calculate.R")

#Parameters:

    # input_receptor.csv: receptor geo data set required columns : unique id , latitude,	longitude 
    # source_xyz_facilities.csv: your facilities site required columns: ID Address,City,State,County	
    # sample data can be downloaded from national priorities list data for new tool (EPA Superfund sites in 2014 via CIESIN (URL): 
    # https://sedac.ciesin.columbia.edu/data/set/superfund-epa-national-priorities-list-ciesin-mod-v2
    # input_us_borders.rds can be download from github URL  
    # buffer_distance_km: The distance from the interested point (NPL facility) rang (1000km  0.001km)
    # assessment_year: The year which exposure assessment set to
    # start_year, end_year: The range of the time frame we consider 
    # time_option : ['single_year_only', 'either_single_or_variable_year','variable_year_only' ]
    # Currently only 'single_year_only' available
    # add_nearest_source : If need frame with point receptors with nearest source details and distance
npl_proximity_metrics_v3 <- 
  #get_xyz_facility_proximity_for_points_V3(
    get_proximity_for_points_V3(
    receptor_xyz_filepath = "./input/input_receptor.csv", 
    source_xyz_facilities_filepath ="./input/EPA_NPL_Site_2014.csv",
    us_borders_filepath ="./input/input_us_borders.rds",
    buffer_distance_km = 10,
    assessment_year = '2017-10-01',
    time_option = 'single_year_only', #'either_single_or_variable_year'#'variable_year_only' 
    check_near_us_border = TRUE,
    add_all_to_output = TRUE,
    print_log_to_console = TRUE,
    write_log_to_file = TRUE
  
    )

# Write exposures to CSV
readr::write_csv(npl_proximity_metrics_v3, 
                 file ="./output/output_xyz_proximity_metrics_V3.csv")

```

## Run version 2.0

### Invoke an r script with multiple sub r script files each file handle one task

### All steps in a big file


### script_npl_proximity_for_points_V2.R

```{r}

# Download national priorities list data for new tool (EPA Superfund sites in 2014 via CIESIN (URL): 
# https://sedac.ciesin.columbia.edu/data/set/superfund-epa-national-priorities-list-ciesin-mod-v2

# Load packages
library(tidyverse)
library(logr)
library(sf)

# Load functions
source("./script_npl_proximity_for_points_V2.R")
source("./functions/npl_proximity_points_logging.R")
source("./functions/npl_proximity_points_input_validation.R")
source("./functions/check_point_receptor_format.R")
source("./functions/npl_proximity_points_transform_calculate.R")
source("./functions/npl_check_point_receptor_format.R")
source("./functions/check_point_receptor_near_border.R")
source("./functions/nearest_distance_to_point_source_for_point_receptor.R")
source("./functions/npl_proximity_points_summary_metrics.R")
source("./functions/npl_summary_of_point_sources_in_buffer_of_point_receptor.R")
                    #npl_summary_of_point_sources_in_buffer_of_point_receptor.R
#Parameters:
    # buffer_distance_km: The distance from the interested point (NPL facility) rang (1000km  0.001km)
    # NPL_STATUS for filter the input data if NULL then no data filter
    # p_NPL_STATUS has three status 
    # ["Proposed for NPL" "Currently on the Final NPL" "Deleted from the Final NPL"]
    # assessment_year: The year which exposure assessment set to
    # start_year, end_year: The range of the time frame we consider 
    # time_option : keep as is    

npl_proximity_metrics_v2 <- 
  get_npl_facility_proximity_for_points_V2(
    receptor_filepath = "./input/input_receptor.csv", 
    source_npl_facilities_filepath ="./input/epa-national-priorities-list-ciesin-mod-v2-2014.xls",
    us_borders_filepath ="./input/input_us_borders.rds",
    buffer_distance_km = 10,
    p_NPL_Status = 'Deleted from the Final NPL',
    assessment_year = '2017-10-01',
    time_option = 'single_year_only' #'either_single_or_variable_year'#'variable_year_only' 
    )

# Write exposures to CSV
readr::write_csv(npl_proximity_metrics_v2, 
                 file ="./output/output_npl_proximity_metrics_V4.csv")

```

## Run version v1.0

### Invoke an r script with input parameters

### All steps in a big file

### script_npl_proximity_for_points.R

```{r}
# Download national priorities list data for new tool (EPA Superfund sites in 2014 via CIESIN (URL): 
# https://sedac.ciesin.columbia.edu/data/set/superfund-epa-national-priorities-list-ciesin-mod-v2

# Load packages
library(tidyverse)
library(logr)
library(sf)
# Load the readxl package
library(readxl)

# Load functions
source("./script_npl_proximity_for_points.R")

# Get exposures
npl_proximity_metrics <- 
  get_npl_facility_proximity_for_points(
    receptor_filepath = "./input/input_receptor.csv", 
    #npl_points_list <- read_excel("epa-national-priorities-list-ciesin-mod-v2-2014.xls", sheet = "EPA_NPL_Sites_asof_27Feb2014")
    source_aircraft_facilities_filepath ="./input/epa-national-priorities-list-ciesin-mod-v2-2014.xls",
    us_borders_filepath ="./input/input_us_borders.rds",
    # NPL_STATUS for filter the input data if NULL then no data filter
    #1. "Proposed for NPL" 
    #2. "Currently on the Final NPL" 
    #3. "Deleted from the Final NPL"
    NPL_STATUS = 'Deleted from the Final NPL', 
    npl_year = '2017-10-01',
    start_year = 1985,
    end_year = 2020
    )
print(ncol(npl_proximity_metrics))
print(nrow(npl_proximity_metrics))
print(colnames(npl_proximity_metrics))
# Write exposures to CSV
readr::write_csv(npl_proximity_metrics, 
                 file ="./output/output_npl_proximity_metrics_v1.csv")

```

#. code block converting geometry data to longitude and latitude

```{r}
library(tidyverse)
# Load necessary libraries
library(dplyr)
#library(tidyr)

# Sample data
data_frame <- data.frame(geometry1 = c("c(-588606.452401901, -880680.305667414)", "c(-123456.789, -987654.321)"))

# Using dplyr and tidyr to separate the columns
data_frame <- data_frame %>%
  mutate(geometry1= gsub("[^0-9.,-]", "", geometry1)) %>% # Clean the geometry column
  separate(geometry1, into = c("longitude", "latitude"), sep = ",", convert = TRUE)
print(data_frame)

```